name: docker
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Get version
        uses: actions/checkout@v2
        run: |
          export VERSION=$(grep version setup.py | cut -f2 -d "'")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker and push to Dockerhub
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ env.VERSION }}
