name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install package
        run: python setup.py install
      - name: Test via pytest
        run: python -m pytest --cov=./ufjc --cov-report xml
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make tarball
        run: python setup.py sdist
      - name: Make wheel
        run: python setup.py bdist_wheel
      - name: Artifact dist/
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: dist/
