name: publish
on:
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  pypi:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Make tarball
        run: python setup.py sdist
      - name: Make wheel
        run: python setup.py bdist_wheel
      - name: Upload to PyPI.org
        run: twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
  anaconda:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare conda
        run: |
          rm -rf ufjc/
          conda update conda
          conda install anaconda-client conda-build
      - name: Create conda recipe from PyPI
        run: conda skeleton pypi --noarch-python ${REPO_NAME}
      - name: Build conda packages
        run: |
          conda build --python 3.6 ${REPO_NAME}
          conda build --python 3.7 ${REPO_NAME}
          conda build --python 3.8 ${REPO_NAME}
      - name: Upload to Anaconda.org
        run: |
          source ~/.bashrc
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          anaconda upload /usr/share/miniconda/noarch/linux-64/*
          anaconda logout