name: paper
on:
  push:
    branches: [ joss ]
  pull_request:
    branches: [ joss ]
  workflow_dispatch:
jobs:
  paper:
    runs-on: ubuntu-20.04
    name: draft
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: figure
        run: python docs/figure.py
      - name: build
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/paper.md
      - name: artifact
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: docs/paper.pdf
