name: paper
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  paper:
    runs-on: ubuntu-20.04
    name: Paper
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/paper.md
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: paper.pdf
          path: docs/paper.pdf
